### ISSUE TITLE
Productos sin validaciones 

### ISSUE THREAD

**Issue by KatuGT** [lucianobonilla27/InventoryIQ-Back#5]
Primero probe enviar un producto con los campos vacios y fueron aceptados
![image](https://github.com/lucianobonilla27/InventoryIQ-Back/assets/38865485/db85496e-1871-4437-a969-759f849ce1cd)

Luego probe mandar un producto totalmente vacio y lo acepto
![image](https://github.com/lucianobonilla27/InventoryIQ-Back/assets/38865485/cab44797-7b7e-4c12-9d0b-91f2411223e3)

agreguen validaciones minimas por favor, tampoco siquiera solicita ser logueado ni mucho menos ser administrador

![image](https://github.com/lucianobonilla27/InventoryIQ-Back/assets/38865485/b4c44be4-d43f-4b1c-bfc1-1c8b67e23a78)

**Comment by lucianobonilla27** [comment]
corregido

**Comment by KatuGT** [comment]
Listo!
